In [116]:
from FrozenYoghourt.mode import Mode as r
from FrozenYoghourt.gates import Gates as g
from FrozenYoghourt.maths import Maths as m
from FrozenYoghourt.quantum import Quantum as q

In [117]:
from typing import *

In [119]:
g = m.to_su(random_unitary(4).data)
L, R = to_su(random_local_ops(2, 2))
h = L@g@R

AttributeError: 'numpy.ndarray' object has no attribute 'det'

In [ ]:
E = g.Magic()

In [346]:
g = m.to_su(random_unitary(4).data)
L, R = to_su(random_local_ops(2, 2))
h = L@g@R

g, h = m.to_su(g), m.to_su(h)

u, v = np.conj(E).T @ g @ E, np.conj(E).T @ h @ E

D1, P1 = np.linalg.eig(u @ u.T)
D2, P2 = np.linalg.eig(v @ v.T)

idx = np.abs(np.real(D1)).argsort()[::-1]
D1 = D1[idx]
P1 = P1[:, idx]

aae(P1@np.diag(D1)@P1.T, u@u.T)

idx = np.abs(np.real(D2)).argsort()[::-1]
D2 = D2[idx]

P2 = P2[:, idx]

if not np.all(np.isclose(D1, D2)):
    print('Case 2')
    D2 = -D2
    aae(P2@np.diag(D2)@P2.T, -v@v.T)

else:
    print('Case 1')
    aae(P2@np.diag(D2)@P2.T, v@v.T)

Case 1


In [347]:
a = P1.T
b = P2.T

In [350]:
aae(a@u@u.T@a.T, b@v@v.T@b.T)

In [351]:
c = np.conj(v).T @ b.T @ a @ u

left_coset = E @ b.T @ a @ np.conj(E).T
right_coset = E @ c.T @ np.conj(E).T

In [352]:
view(q.gamma(left_coset))

Matrix([
[1.0,   0,   0,   0],
[  0, 1.0,   0,   0],
[  0,   0, 1.0,   0],
[  0,   0,   0, 1.0]])

In [353]:
view(q.gamma(right_coset))

Matrix([
[1.0,   0,   0,   0],
[  0, 1.0,   0,   0],
[  0,   0, 1.0,   0],
[  0,   0,   0, 1.0]])

In [197]:
view(q.chi(u@u.T))

Matrix([
[                           1.0],
[-0.6501620451 + 0.0873356367*I],
[                    1.78908392],
[-0.6501620451 - 0.0873356367*I],
[                           1.0]])

In [264]:
D1

array([ 0.8649451 +0.50186649j, -0.69587342+0.71816445j,
        0.46223007-0.88676004j, -0.2036678 -0.97904005j])

In [257]:
D1, D2

(array([ 0.8649451 +0.50186649j, -0.69587342+0.71816445j,
         0.46223007-0.88676004j, -0.2036678 -0.97904005j]),
 array([-0.8649451 -0.50186649j,  0.69587342-0.71816445j,
        -0.46223007+0.88676004j,  0.2036678 +0.97904005j]))

In [ ]:
if not np.isclose(D1[0], D2[0]):
    D2 = -D2
    P2 = 1j*P2

In [187]:
view(q.chi(v@v.T))

Matrix([
[                          1.0],
[0.0652594175 + 0.3831728553*I],
[                 0.0686478628],
[0.0652594175 - 0.3831728553*I],
[                          1.0]])

In [189]:
view(P1.T@u@u.T@P1)

Matrix([
[-0.7911017155 + 0.6116846211*I,                             0,                             0,                             0],
[                             0, 0.7627835467 + 0.6466538957*I,                             0,                             0],
[                             0,                             0, -0.5893067756 - 0.807909354*I,                             0],
[                             0,                             0,                             0, 0.5523655269 - 0.8336020182*I]])

In [190]:
view(P2.T@v@v.T@P2)

Matrix([
[-0.7911017155 + 0.6116846211*I,                             0,                             0,                             0],
[                             0, 0.7627835467 + 0.6466538957*I,                             0,                             0],
[                             0,                             0, -0.5893067756 - 0.807909354*I,                             0],
[                             0,                             0,                             0, 0.5523655269 - 0.8336020182*I]])

In [155]:
a = P1
b = P2

c = np.conj(v).T @ b.T @ a @ u

left_coset = np.conj(E).T @ b.T @ a @ E

In [157]:
view(D1)

Matrix([
[ 0.9598139709 - 0.2806370278*I],
[ 0.8830328258 + 0.4693112278*I],
[-0.9489079892 + 0.3155528927*I],
[-0.9931648924 - 0.1167197352*I]])

In [158]:
view(D2)

Matrix([
[ 0.9258405788 - 0.3779143059*I],
[-0.7005123937 - 0.7136402359*I],
[ 0.0945097089 - 0.9955239399*I],
[-0.4809952521 - 0.8767231989*I]])

In [139]:
view(q.chi(q.gamma(u)))

Matrix([
[                           1.0],
[-0.9817608421 + 0.3708473738*I],
[                  0.2673700002],
[-0.9817608421 - 0.3708473738*I],
[                           1.0]])

In [140]:
view(q.chi(q.gamma(u)))

Matrix([
[                           1.0],
[-0.9817608421 + 0.3708473738*I],
[                  0.2673700002],
[-0.9817608421 - 0.3708473738*I],
[                           1.0]])

In [122]:
D1

array([ 0.95778026-0.28750127j,  0.69474595-0.71925521j,
       -0.54185165-0.84047415j, -0.99537741-0.0960407j ])

In [123]:
D2

array([ 0.95778026-0.28750127j,  0.69474595-0.71925521j,
       -0.54185165-0.84047415j, -0.99537741-0.0960407j ])

In [113]:
def double_cosets(g, h):
    E = Gates.Magic()

    g, h = Maths.to_su(g), Maths.to_su(h)

    u, v = np.conj(E).T @ g @ E, np.conj(E).T @ h @ E

    D1, P1 = np.linalg.eig(u @ u.T)
    D2, P2 = np.linalg.eig(v @ v.T)

    idx = D1.argsort()[::-1]
    D1 = D1[idx]
    P1 = P1[:, idx]

    idx = D2.argsort()[::-1]
    D2 = D2[idx]
    P2 = P2[:, idx]

    if not np.isclose(D1[0], D2[0]):
        D2 = -D2
        idx = D2.argsort()[::-1]
        D2 = D2[idx]
        P2 = P2[:, idx]

    a = P1.T
    b = P2.T

    c = np.conj(v).T @ b.T @ a @ u

    left_coset = E @ b.T @ a @ np.conj(E).T
    right_coset = E @ c.T @ np.conj(E).T

    return left_coset, right_coset



TypeError: double_cosets() missing 2 required positional arguments: 'g' and 'h'